name: CI

on:
  push:
  workflow_call:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - uses: seanmiddleditch/gha-setup-ninja@v6
      - uses: actions/cache@v4
        with:
          path: ./build
          key: ${{ runner.os }}-cmake-${{ hashFiles('CMakeLists.txt') }}
      - name: Configure CMake
        run: cmake --preset release
      - name: Build
        run: cmake --build --preset release --target all
